### ISSUE TITLE
meraki_networks_firmware_upgrades throws error when `products` set

### ISSUE THREAD

**Issue by zbuchheit** [cisco-open/terraform-provider-meraki#108]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/meraki/terraform-provider-meraki/tree/main#compatibility-matrix) before opening an issue. 

## **Describe the bug**
When attempting to use meraki_networks_firmware_upgrades with `products` set I get the following error back from the API
```
    BODY         :
    {
       "errors": [
          "camera does not exist in selected network",
          "sensor does not exist in selected network"
       ]
    }
```

## **Expected behavior**
I would expect the resource to create successfully with my desired nextUpgrade value.

## **Example Code**
```tf

terraform {
  required_providers {
    meraki = {
      source = "cisco-open/meraki"
      version = "0.2.5-alpha"
    }
  }
}

provider "meraki" {
  meraki_debug = "true"
}

resource "meraki_networks_firmware_upgrades" "firmware_upgrades" {
  network_id = "redacted"
  timezone = "America/Los_Angeles"
  upgrade_window = {
    day_of_week = "thu"
    hour_of_day = "23:00"
  }
  products = {
    wireless = {
      next_upgrade = {
        time = "2024-08-10T23:00:00Z"
        to_version = {
          id = "3183"
        }
      }
    }
  }
}

```

**Environment (please complete the following information):**
* Meraki Dashboard version: 
* Terraform version:
* Meraki provider version:  "0.2.5-alpha"
* OS Version: 

**Additional context**

**Comment by fmunozmiranda** [comment]
Do you test it directly in API? It works?

**Comment by zbuchheit** [comment]
API is fine, it seems because the PUT via the provider is getting sent with `camera` and `sensor` as `{}` despite it not being contained in the code and also it doesn't exist on the network I am working with.
```
 BODY   :
    {
       "products": {
          "appliance": {
             "nextUpgrade": {
                "toVersion": {}
             },
             "participateInNextBetaRelease": false
          },
          "camera": {},
          "cellularGateway": {
             "nextUpgrade": {
                "toVersion": {}
             },
             "participateInNextBetaRelease": false
          },
          "sensor": {},
          "switch": {
             "nextUpgrade": {
                "toVersion": {}
             },
             "participateInNextBetaRelease": false
          },
          "wireless": {
             "nextUpgrade": {
                "time": "2024-08-10T23:00:00Z",
                "toVersion": {
                   "id": "3183"
                }
             },
             "participateInNextBetaRelease": false
          }
       },
       "timezone": "America/Los_Angeles",
       "upgradeWindow": {
          "dayOfWeek": "thu",
          "hourOfDay": "23:00"
       }
    }
    ------------------------------------------------------------------------------
```

When I use a GET to query the values there is no camera or sensor so the API call I would want/expect the provider to make would be the same as above just without `"sensor": {},` and `"camera": {},`

**Comment by fmunozmiranda** [comment]
If we do not receive a response it will be closed in the next 24 hours.
