### ISSUE TITLE
meraki_devices_management_interface (Data Source) error on read data switches

### ISSUE THREAD

**Issue by Landru-80** [cisco-open/terraform-provider-meraki#109]
**Describe the bug**
if i tried to read out the data from 
meraki_devices_management_interface 

data "meraki_devices_management_interface" "cat9300" {
  serial = "XXXX-XXXX-XXXX"
}
output "meraki_devices_management_interface_cat9300" {
  value = data.meraki_devices_management_interface.cat9300.item
}

I got this error 

│ Expected framework type from provider logic: types.ListType[basetypes.StringType] / underlying type: tftypes.List[tftypes.String]
│ Received framework type from provider logic: types.ListType[!!! MISSING TYPE !!!] / underlying type: tftypes.List[tftypes.DynamicPseudoType]
│ Path: item.wan2.static_dns

Device ist a Catalyst 9300-M , a switch of catalyst series for meraki.

Same error if i try to set the management interface.

**Environment (please complete the following information):**
* Meraki Dashboard version: 
* Terraform version:  Terraform v1.9.2
                                   on darwin_arm64
* Meraki provider version: provider registry.terraform.io/cisco-open/meraki v0.2.5-alpha
* OS Version: MacOS14.5

**Comment by fmunozmiranda** [comment]
@Landru-80  please try it again with new version and update us.

**Comment by Landru-80** [comment]
Hi,
to read the data out is working

```
 data "meraki_devices_management_interface" "example" {
 serial = "aaaa-bbbb-cccc-ddd"
}

OUT:
+ meraki_devices_management_interface_example = {
      + ddns_hostnames = null
      + wan1           = {
          + static_dns         = [
              + "10.1.1.1",
              + "10.1.1.2",
            ]
          + static_gateway_ip  = "10.1.2.1"
          + static_ip          = "10.1.2.200"
          + static_subnet_mask = "255.255.255.0"
          + using_static_ip    = true
          + vlan               = 2
          + wan_enabled        = ""
        }
      + wan2           = null
    }
	
```
But if we try to import it to the terraform state, we got still this error

```
terraform import meraki_devices_management_interface.example "aaaa-bbbb-cccc-dddd"
Error: Value Conversion Error
│
│ An unexpected error was encountered while verifying an attribute value matched its expected type to prevent unexpected behavior or panics. This is always
│ an error in the provider. Please report the following to the provider developer:
│
│ Expected framework type from provider logic: types.SetType[basetypes.StringType] / underlying type: tftypes.Set[tftypes.String]
│ Received framework type from provider logic: types.SetType[!!! MISSING TYPE !!!] / underlying type: tftypes.Set[tftypes.DynamicPseudoType]
│ Path: wan2.static_dns
```

Resource  definition is

```
	resource "meraki_devices_management_interface" "example" {
	  serial = "aaaa-bbbb-cccc-dddd"
	  wan1 = {
	    static_dns         = ["10.1.1.1", "10.1.1.2"]
	    static_gateway_ip  = "10.1.2.1"
	    static_ip          = "10.1.2.201"
	    static_subnet_mask = "255.255.255.0"
	    using_static_ip    = true
	    vlan               = 2
	    wan_enabled        = ""
	  }
	  wan2 = null
	}
```

**Comment by fmunozmiranda** [comment]
Please try it with new version.

**Comment by fmunozmiranda** [comment]
If we do not receive a response it will be closed in the next 24 hours.

**Comment by Landru-80** [comment]
Hi,
sorry for the late response.

Yes i could successfully set the management interface for this devices AccessPoint MR46 and Catalyst C9300-M.
All works fine.

Thank you for your fast help and solution

Best Regards
