### ISSUE TITLE
Encountering panic in latest version when attempting to create `meraki_networks (Resource)`

### ISSUE THREAD

**Issue by zbuchheit** [cisco-open/terraform-provider-meraki#111]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/meraki/terraform-provider-meraki/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
When attempting to create a `meraki_networks` resource it panics on creation of the resource.

**Expected behavior**
Able to correctly create a merak_networks resource.

**Screenshots**
```tf

resource meraki_networks "example" {
  name = "My Test Network"
  organization_id = "redacted"
  notes = "This is a test network created by my team"
  product_types = ["appliance", "switch", "wireless", "cellularGateway"]
  time_zone = "America/Los_Angeles"
}
```

```
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-meraki_v0.2.6-alpha plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x10484eda8]

goroutine 12 [running]:
github.com/cisco-open/terraform-provider-meraki/internal/provider.(*NetworksResource).Create(0x140003940a8, {0x105467d68, 0x140001f8cc0}, {{{{0x10546f9a8, 0x140002041b0}, {0x1051ec180, 0x140001f9c50}}, {0x105481b48, 0x140000983c0}}, {{{0x10546f9a8, ...}, ...}, ...}, ...}, ...)
        github.com/cisco-open/terraform-provider-meraki/internal/provider/resource_meraki_networks.go:189 +0x5f8
```

**Environment (please complete the following information):**
* Meraki Dashboard version: 
* Terraform version: v0.2.6-alpha
* Meraki provider version:
* OS Version: 

**Additional context**

**Comment by fmunozmiranda** [comment]
Please try it with new version.

**Comment by zbuchheit** [comment]
that does appear to fix it. Thanks!

**Comment by fmunozmiranda** [comment]
Thank you for your feedback.
