### ISSUE TITLE
resources meraki_networks_group_policies update error

### ISSUE THREAD

**Issue by Fran-E** [cisco-open/terraform-provider-meraki#117]
**Prerequisites**
* [no] Have you tested the operation in the API directly?
* [yes] Do you have the latest Terraform provider version?
* [yes] Review the [compatibility matrix](https://github.com/meraki/terraform-provider-meraki/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
About resources meraki_networks_group_policies when we are using firewall_and_traffic_shaping.l3_firewall_rules there is always modify discoverd during the plan and the apply do error.

**Expected behavior**
Possibility to update firewall_and_traffic_shaping.l3_firewall_rules in the resource meraki_networks_group_policies without error with a plan working.

**Screenshots**
This is the error when we apply : 
│ Error: Failure when executing UpdateNetworkGroupPolicy
│
│   with meraki_networks_group_policies.policynetatmo["ABBEVILLECB-MX"],
│   on grouppolicy.tf line 1, in resource "meraki_networks_group_policies" "policynetatmo":
│    1: resource "meraki_networks_group_policies" "policynetatmo" {
│
│ error with operation UpdateNetworkGroupPolicy
╵

**Environment (please complete the following information):**
* Meraki Dashboard version: ?
* Terraform version: 1.9.2
* Meraki provider version: 0.2.9-alpha
* OS Version: Windows 11

**Comment by fmunozmiranda** [comment]
Could you please pass us the provider debug?
```hcl
provider "meraki" {
  meraki_debug = "true"
}
```
```zsh
export TF_LOG="DEBUG"
```

**Comment by Fran-E** [comment]
[debug.txt](https://github.com/user-attachments/files/16437639/debug.txt)

I think the interesting part is here : 

> 2024-07-31T09:05:03.064+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe: ~~~ RESPONSE ~~~
> 2024-07-31T09:05:03.064+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe: STATUS       : 400 Bad Request
> 2024-07-31T09:05:03.065+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe: PROTO        : HTTP/2.0
> 2024-07-31T09:05:03.065+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe: RECEIVED AT  : 2024-07-31T09:05:03.0316399+02:00
> 2024-07-31T09:05:03.065+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe: TIME DURATION: 340.6106ms
> 2024-07-31T09:05:03.065+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe: HEADERS      :
> 2024-07-31T09:05:03.065+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe:       Cache-Control: no-cache, no-store, max-age=0, must-revalidate
> 2024-07-31T09:05:03.065+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe:       Content-Type: application/json; charset=utf-8
> 2024-07-31T09:05:03.065+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe:       Date: Wed, 31 Jul 2024 07:05:03 GMT
> 2024-07-31T09:05:03.065+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe:       Expires: Fri, 01 Jan 1990 00:00:00 GMT
> 2024-07-31T09:05:03.065+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe:       Pragma: no-cache
> 2024-07-31T09:05:03.065+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe:       Strict-Transport-Security: max-age=31536000; includeSubDomains
> 2024-07-31T09:05:03.065+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe:       X-Content-Type-Options: nosniff
> 2024-07-31T09:05:03.065+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe:       X-Frame-Options: sameorigin
> 2024-07-31T09:05:03.065+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe:       X-Request-Id: b261e2608935d9a0ea720c72aa917f21
> 2024-07-31T09:05:03.065+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe:       X-Robots-Tag: none
> 2024-07-31T09:05:03.065+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe:       X-Runtime: 0.193754
> 2024-07-31T09:05:03.065+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe:       X-Xss-Protection: 1; mode=block
> 2024-07-31T09:05:03.065+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe: BODY         :
> 2024-07-31T09:05:03.065+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe: {
> 2024-07-31T09:05:03.065+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe:    "errors": [
> 2024-07-31T09:05:03.065+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe:       "**Content Filtering settings are not supported for your network. Consider upgrading your devices to enable this feature**."
> 2024-07-31T09:05:03.065+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe:    ]
> 2024-07-31T09:05:03.066+0200 [DEBUG] provider.terraform-provider-meraki_v0.2.9-alpha.exe: }
> 2024-07-31T09:05:03.065+0200 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot

We don't have full licenses on our MX devices and the API call is always sending "contentFiltering" argument, I don't have this in my TF file. I try to add   
lifecycle {
    ignore_changes = [content_filtering]
  }
But I have the same error.

Br,

**Comment by fmunozmiranda** [comment]
@Fran-E  please try it with new version and update us.

**Comment by Fran-E** [comment]
I can confirm this is solve now. Thanks.
