### ISSUE TITLE
`meraki_devices_management_interface` resource seems to be broken

### ISSUE THREAD

**Issue by mobig** [cisco-open/terraform-provider-meraki#12]
**Prerequisites**
* [NO] Have you tested the operation in the API directly?
* [YES] Do you have the latest Terraform provider version?
* [can't find doc] Review the [compatibility matrix](https://github.com/meraki/terraform-provider-meraki/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
When running the following TF:

```
terraform {
  required_providers {
    meraki = {
      source  = "cisco-open/meraki"
      version = "0.1.0-alpha"

    }
  }
}

provider "meraki" {
  meraki_dashboard_api_key = "<key>"
}

resource "meraki_devices_management_interface" "example" {
  serial = "<device_serial>"
  wan1   = {
    static_gateway_ip  = "192.168.0.1"
    static_ip          = "192.168.0.50"
    static_subnet_mask = "255.255.255.0"
    using_static_ip    = true
    static_dns         = ["192.168.0.1", "8.8.8.8"]
    vlan               = 1
  }
}
```

i get this error
```
meraki_devices_management_interface.example: Creating...
╷
│ Error: Value Conversion Error
│
│   with meraki_devices_management_interface.example,
│   on main.tf line 43, in resource "meraki_devices_management_interface" "example":
│   43: resource "meraki_devices_management_interface" "example" {
│
│ An unexpected error was encountered while verifying an attribute value matched its expected type to prevent unexpected behavior or panics. This is always an error in the provider. Please report the following to the provider developer:
│
│ Expected framework type from provider logic: types.SetType[basetypes.StringType] / underlying type: tftypes.Set[tftypes.String]
│ Received framework type from provider logic: types.SetType[!!! MISSING TYPE !!!] / underlying type: tftypes.Set[tftypes.DynamicPseudoType]
│ Path: wan2.static_dns
```
i'm running this against a `MS425-32` switch. For some reason, it's saying the path error is `Path: wan2.static_dns`. The [docs ](https://registry.terraform.io/providers/cisco-open/meraki/latest/docs/resources/devices_management_interface)for the resource state that wan2 is used only for MX devices and is optional, but it seems that the provider os still trying to configure wan2. 

**Expected behavior**
i would expect this resource to work as advertised in setting the mgmt perameraters for a device

**Environment (please complete the following information):**
* Meraki Dashboard version: No idea where to find this. It's the current version
* Terraform version: v1.4.2
* Meraki provider version: v0.1.0-alpha
* OS Version: Windows 11

**Comment by obrigg** [comment]
Can you kindly try using the [meraki_networks_switch_alternate_management_interface](https://registry.terraform.io/providers/cisco-open/meraki/latest/docs/resources/networks_switch_alternate_management_interface) for switches?

**Comment by mobig** [comment]
> Can you kindly try using the [meraki_networks_switch_alternate_management_interface](https://registry.terraform.io/providers/cisco-open/meraki/latest/docs/resources/networks_switch_alternate_management_interface) for switches?

AMI works if i don't set the gateway and mask. 

Working code:
```
resource "meraki_networks_switch_alternate_management_interface" "example" {
  network_id = "<network_id>"
  switches = [{
    alternate_management_ip = "1.2.3.1"
    serial                  = "<device_serial#>"
  }]
}
```
In reading the docs for MS switch AMIs, it seems that the mask and gateway are derived from the L3 interface of the VLAN you give the AMI. i'm not sure why they included subnet and gateway fields in the API.

This seems to have no correlation with the meraki_devices_management_interface issue

**Comment by obrigg** [comment]
I am looking into this. It does not look like a TF issue but has something do to with the API operation itself.

**Comment by mobig** [comment]
Just looking for an update. Has there been any progress on this?

Thanks

**Comment by obrigg** [comment]
Thank you for your patience.
We're preparing a significant update with improved coverage, as well as fixes to several of the reported issues. We'll make sure this issue is being addressed too.

**Comment by fmunozmiranda** [comment]
Closed due inactivity
