### ISSUE TITLE
Fix import statement for `meraki_networks_vlan_profiles`

### ISSUE THREAD

**Issue by zbuchheit** [cisco-open/terraform-provider-meraki#120]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/meraki/terraform-provider-meraki/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
The import statement appears to be incorrectly documented as `terraform import meraki_networks_vlan_profiles.example "iname,network_id"` but in testing that doesn't work and the correct import statement is `terraform import meraki_networks_vlan_profiles.example "network_id,iname"` where network_id comes after iname. 

**Expected behavior**
Document the correct import statement for the resource.

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.

**Environment (please complete the following information):**
* Meraki Dashboard version: 
* Terraform version:
* Meraki provider version:
* OS Version: 

**Additional context**

**Comment by fmunozmiranda** [comment]
Ready
