### ISSUE TITLE
meraki_networks_switch_port_schedules - inconsistent reply

### ISSUE THREAD

**Issue by mcparaf** [cisco-open/terraform-provider-meraki#124]
**Prerequisites**
* [ v ] Have you tested the operation in the API directly?
* [ v ] Do you have the latest Terraform provider version?
* [ x ] Review the [compatibility matrix](https://github.com/meraki/terraform-provider-meraki/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
After trying to create `meraki_networks_switch_port_schedules` Terraform complains that there is an inconsistent reply in the provider:
```
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.meraki.meraki_networks_switch_port_schedules.net_switch_port_schedules["0"], provider "module.meraki.provider[\"registry.terraform.io/cisco-open/meraki\"]" produced an unexpected new value: .network_id: was
│ cty.StringVal("L_709316941310853998"), but now null.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```
I am not sure which requests are relevant to this or what more data to provide. I can see only GET requests that are being run by the provider. If there is any more context necessary please feel free to contact me and I will gladly help.

**Environment (please complete the following information):**
* Meraki Dashboard version: n260.meraki.com
* Terraform version: 1.9.1
* Meraki provider version: 0.2.9-alpha
* OS Version: macOS Sonoma 14.5

**Comment by fmunozmiranda** [comment]
@mcparaf please try it with new version and update us.

**Comment by mcparaf** [comment]
This is working now.
