### ISSUE TITLE
Error when manually setting meraki_devices_wireless_radio_settings channel width

### ISSUE THREAD

**Issue by txraider09** [cisco-open/terraform-provider-meraki#125]
After manually setting the channel_width on meraki_devices_wireless_radio_settings instead of auto-channel, the following error happens during the next plan.

│ Error: Failure when executing GetDeviceWirelessRadioSettings
│ 
│   with meraki_devices_wireless_radio_settings.example,
│   on wireless_radio_settings.tf line 1, in resource "meraki_devices_wireless_radio_settings" "example":
│    1: resource "meraki_devices_wireless_radio_settings" "example" {
│ 
│ json: cannot unmarshal string into Go struct field ResponseWirelessGetDeviceWirelessRadioSettingsFiveGhzSettings.fiveGhzSettings.channelWidth of type int

**Comment by fmunozmiranda** [comment]
@txraider09  please try it with new version and update us.

**Comment by fmunozmiranda** [comment]
Closed due inactivity
