### ISSUE TITLE
Document error to import meraki_networks_group_policies

### ISSUE THREAD

**Issue by Fran-E** [cisco-open/terraform-provider-meraki#126]
**Prerequisites**
* [no] Have you tested the operation in the API directly?
* [yes] Do you have the latest Terraform provider version?
* [yes] Review the [compatibility matrix](https://github.com/meraki/terraform-provider-meraki/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
There is a small mistake in the import syntax about the ressource meraki_networks_group_policies

This is write : terraform import meraki_networks_group_policies.example "group_policy_id,network_id"
But it works with terraform import meraki_networks_group_policies.example "network_id,group_policy_id"

**Comment by fmunozmiranda** [comment]
Ready.
