### ISSUE TITLE
Allow ability to disable 2.4Ghz radio

### ISSUE THREAD

**Issue by txraider09** [cisco-open/terraform-provider-meraki#127]
When running a data lookup on radio settings, a disabled 2.4 radio returns -1 as a value for target_power. When setting -1 in a resource, it errors out.

  # meraki_devices_wireless_radio_settings.example will be created
  + resource "meraki_devices_wireless_radio_settings" "example" {
      + five_ghz_settings     = {
          + channel       = 56
          + channel_width = (known after apply)
          + target_power  = 8
        }
      + rf_profile_id         = (known after apply)
      + serial                = "serial_number"
      + two_four_ghz_settings = {
          + channel      = 1
          + target_power = -1
        }
    }

Error when trying to set resource target_power to -1:

│ Error: Failure when executing UpdateDeviceWirelessRadioSettings
│ 
│   with meraki_devices_wireless_radio_settings.example,
│   on wireless_radio_settings.tf line 23, in resource "meraki_devices_wireless_radio_settings" "example":
│   23: resource "meraki_devices_wireless_radio_settings" "example" {
│ 
│ error with operation UpdateDeviceWirelessRadioSettings

**Comment by fmunozmiranda** [comment]
Could you please pass us the provider debug?
```hcl
provider "meraki" {
  meraki_debug = "true"
}
```
```zsh
export TF_LOG="DEBUG"
```
@txraider09

**Comment by obrigg** [comment]
Hello,
The accepted target power for 2.4GHz radio is between 5 and 30. The API call should fail for this setting.

**Comment by obrigg** [comment]
Closing this issue, as Terraform can't provide functionality the API doesn't provide.
