### ISSUE TITLE
MERAKI_DEBUG environment variable doesn't work

### ISSUE THREAD

**Issue by zbuchheit** [cisco-open/terraform-provider-meraki#131]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/meraki/terraform-provider-meraki/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
When attempting to use MERAKI_DEBUG=true environment variable with the provider, it doesn't appear to work. Setting it explicitly on the provider works.

**Expected behavior**
Allow use of environment variable MERAKI_DEBUG to get additional debug logs and api calls.

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.

**Environment (please complete the following information):**
* Meraki Dashboard version: 
* Terraform version: 0.2.9-alpha
* Meraki provider version:
* OS Version: 

**Additional context**

**Comment by zbuchheit** [comment]
hi, thanks for the speedy response.

I am on macOS 14.2.1 I have tried zsh and bash and neither seem to work for me. 

This is my minimal setup

```tf
terraform {
  required_providers {
    meraki = {
      source = "cisco-open/meraki"
      version = "0.2.9-alpha"
    }
  }
}

data "meraki_devices" "example" {
  organization_id = redacted
}
```

running `TF_LOG=debug MERAKI_DEBUG="true" terraform plan` and running the export permutations doesn't seem to work either.

**Comment by obrigg** [comment]
Hi Zach,
Can you kindly add `meraki_debug = "true"` in the TF file?

```
terraform {
  required_providers {
    meraki = {
      version = "0.2.9-alpha"
      source = "cisco-open/meraki"
    }
  }
}
provider "meraki" {
  meraki_debug = "true"
}
```

**Comment by zbuchheit** [comment]
yeah, when I do that it is able to debug as desired. It just doesn't appear to work with the environment variable.

**Comment by obrigg** [comment]
I see. We can look at making it clearer that this is a configuration in the TF file and not an environment variable (as opposed to TF_LOG=DEBUG, required by Terraform).

**Comment by zbuchheit** [comment]
The docs detail it should work
https://registry.terraform.io/providers/cisco-open/meraki/latest/docs

and looking in the code at a quick glance it looks like it should work but I am unsure why it isn't working for me
https://github.com/cisco-open/terraform-provider-meraki/blob/f64fb0a70e9026ee7629cfbebb5eed24adec8551/internal/provider/provider.go#L138

There are instances where it would be more convenient to just use the env variable as opposed to explicitly in the code itself.

**Comment by fmunozmiranda** [comment]
@zbuchheit please try it with new version and update us.

**Comment by zbuchheit** [comment]
it looks to be working now with the latest version. Thanks!
