### ISSUE TITLE
Unable to create new wireless RF profile if using band_selection_type = "ssid" attribute

### ISSUE THREAD

**Issue by efernando87** [cisco-open/terraform-provider-meraki#136]
**Prerequisites**
* [V] Have you tested the operation in the API directly?
* [V] Do you have the latest Terraform provider version?
* [V] Review the [compatibility matrix](https://github.com/meraki/terraform-provider-meraki/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
Unable to create new wireless RF profile when we are using band_selection_type set to "ssid" and using per_ssid_settings
example code as below
```
resource "meraki_networks_wireless_rf_profiles" "test_rf_profiles" {
  network_id               = meraki_networks.network.network_id
  band_selection_type      = "ssid"
  client_balancing_enabled = false
  name                     = "Testing Indoor Profile"
  five_ghz_settings = {
    channel_width = "20"
    max_power     = 30
    min_bitrate   = 24
    min_power     = 12
  }
  two_four_ghz_settings = {
    ax_enabled  = true
    max_power   = 30
    min_bitrate = 24
    min_power   = 8
  }
  per_ssid_settings = {
    status_0 = {
      band_operation_mode   = "dual"
      band_steering_enabled = true
      bands = {
        enabled = ["2.4", "5"]
      }
    }
    status_1 = {
      band_operation_mode   = "2.4ghz"
      band_steering_enabled = false
      bands = {
        enabled = ["2.4"]
      }
    }
    status_2  = local.standard_pssid
    status_3  = local.standard_pssid
    status_4  = local.standard_pssid
    status_5  = local.standard_pssid
    status_6  = local.standard_pssid
    status_7  = local.standard_pssid
    status_8  = local.standard_pssid
    status_9  = local.standard_pssid
    status_10 = local.standard_pssid
    status_11 = local.standard_pssid
    status_12 = local.standard_pssid
    status_13 = local.standard_pssid
    status_14 = local.standard_pssid
  }
}
```
I attached my debug as well

**Expected behavior**
RF profile with per SSID band selection will be able to created smoothly 

**Screenshots**
debug attached 
[terraform meraki debug rf profile.txt](https://github.com/user-attachments/files/16518076/terraform.meraki.debug.rf.profile.txt)

**Environment (please complete the following information):**
* Meraki Dashboard version: 
* Terraform version: 1.9.3
* Meraki provider version: 0.2.10-alpha
* OS Version: 

**Additional context**
This resource are able to be created if we change the band_selection_type to "ap" like this below example 

```
resource "meraki_networks_wireless_rf_profiles" "test_rf_profiles" {
  network_id               = meraki_networks.network.network_id
  band_selection_type      = "ap"
  client_balancing_enabled = false
  name                     = "Testing Indoor Profile"
  five_ghz_settings = {
    channel_width = "20"
    max_power     = 30
    min_bitrate   = 24
    min_power     = 12
  }
  two_four_ghz_settings = {
    ax_enabled  = true
    max_power   = 30
    min_bitrate = 24
    min_power   = 8
  }
  ap_band_settings = {
    band_operation_mode   = "dual"
    band_steering_enabled = true
    bands = {
      enabled = ["2.4", "5"]
    }
  }
}
```

and somehow it works if the profile was created and we change the band_selection_type to "ssid" using the above resource config

**Comment by obrigg** [comment]
Hello,
Can you kindly activate the provider debug and share it?

```
provider "meraki" {
  meraki_debug = "true"
}
```

`export TF_LOG="DEBUG"`

**Comment by fmunozmiranda** [comment]
If we don´t get answer in next 24 hours issue will be closed.

**Comment by efernando87** [comment]
Hi @obrigg 

I have attached the debug log on the .txt file from the begining.

Are you referring to other debug log?

**Comment by fmunozmiranda** [comment]
You have to enable provider debugging.
https://registry.terraform.io/providers/cisco-open/meraki/latest/docs#meraki_debug

**Comment by efernando87** [comment]
Hi @fmunozmiranda ,

the attached [terraform meraki debug rf profile.txt](https://github.com/user-attachments/files/16518076/terraform.meraki.debug.rf.profile.txt) is extract while meraki debugging was enabled.

I have done it previously thats why I attached the debug file from the beginning.
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/e2077c1d-cc1d-4337-8f22-b2a64a736eca">
is that the wrong debug logs?

**Comment by fmunozmiranda** [comment]
Hi @efernando87 sorry for delay, I don´t see the DEBUG, if have it enabled, we must see the API Calls.

**Comment by fmunozmiranda** [comment]
Closed due inactivity
