### ISSUE TITLE
Error `cannot unmarshal number into Go struct field` when attempting to use data "meraki_networks_wireless_ssids_traffic_shaping_rules"

### ISSUE THREAD

**Issue by tienphan181** [cisco-open/terraform-provider-meraki#146]
**Describe the bug**
When I use data "meraki_networks_wireless_ssids_traffic_shaping_rules" I get the following error:
 Error: Failure when executing GetNetworkWirelessSSIDTrafficShapingRules
│ 
│   with data.meraki_networks_wireless_ssids_traffic_shaping_rules.example,
│   on firewall-rules.tf line 67, in data "meraki_networks_wireless_ssids_traffic_shaping_rules" "example":
│   67: data "meraki_networks_wireless_ssids_traffic_shaping_rules" "example" {
│ 
│ json: cannot unmarshal object into Go struct field
│ ResponseWirelessGetNetworkWirelessSSIDTrafficShapingRulesRulesDefinitions.rules.definitions.value
│ of type string

Same error when I try to create a resource "meraki_networks_wireless_ssids_traffic_shaping_rules".

**Expected behavior**
I would expect it to show the data with no errors.

**Environment (please complete the following information):**
Terraform version: OpenTofu v1.7.2
Meraki provider version: 0.2.10-alpha
OS Version: macOS 13.6.7

**Additional context**
```
data "meraki_networks_wireless_ssids_traffic_shaping_rules" "example" {

  network_id = meraki_networks.test-Terraform.id
  number     = 1
}

output "meraki_networks_wireless_ssids_traffic_shaping_rules_example" {
  value = data.meraki_networks_wireless_ssids_traffic_shaping_rules.example.item.rules
}
```

**Comment by fmunozmiranda** [comment]
Hi @tienphan181 could you please pass me debug of provider please?

**Comment by fmunozmiranda** [comment]
if we don´t get answer in next 24 hours issue will be closed.
