### ISSUE TITLE
Add ability to use failoverCriterion with SDWAN traffic shaping internet policies

### ISSUE THREAD

**Issue by zbuchheit** [cisco-open/terraform-provider-meraki#151]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like to be able to use the provider to automate the following endpoint https://developer.cisco.com/meraki/api-v1/update-network-appliance-sdwan-internet-policies/ to configure my SDWAN traffic shaping internet policies

**Describe alternatives you've considered**

**Additional context**

**Comment by obrigg** [comment]
Hi Zach,
The updateNetworkApplianceSdwanInternetPolicies operation is in beta. Once it graduates to GA, it will automatically be included in the following Terraform release.
