### ISSUE TITLE
Add ability to configure the consent message for the splash page on the provider

### ISSUE THREAD

**Issue by zbuchheit** [cisco-open/terraform-provider-meraki#152]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like to be able to configure the splash page consent message via the provider

**Describe alternatives you've considered**

**Additional context**

**Comment by obrigg** [comment]
Hi Zach,
To ensure we're aligned, which API operation (on meraki.io/api) are you referring to?

**Comment by zbuchheit** [comment]
I don't believe the API operation exists yet 

https://community.meraki.com/t5/Developers-APIs/Are-quot-user-consent-quot-and-quot-consent-message-quot-from/m-p/235233

**Comment by obrigg** [comment]
That makes sense. Once we have an API for it - it will be added to our Terraform provider.
You can ask your Meraki account team to add your name to the feature request.
