### ISSUE TITLE
TF_LOG Debugs in non-english language

### ISSUE THREAD

**Issue by noop1001** [cisco-open/terraform-provider-meraki#167]
Hi ,

Would it be possible to change the debug logs to english ?

I see a mix of debugs in english and I think spanish ?

For a consistent experience it would be useful to see these logs in english only.

**Comment by yujiterada** [comment]
I agree the Spanish logs are everywhere.
![image](https://github.com/user-attachments/assets/b7a66209-0026-4ea0-9500-eb11f4334c2e)

**Comment by fmunozmiranda** [comment]
changed.
