### ISSUE TITLE
Random Provider Crashes

### ISSUE THREAD

**Issue by noop1001** [cisco-open/terraform-provider-meraki#170]
**Prerequisites**
* [x ] Have you tested the operation in the API directly?
* [x ] Do you have the latest Terraform provider version?
* [ x] Review the [compatibility matrix](https://github.com/meraki/terraform-provider-meraki/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
I see random provider issues when running the provider in our CI/

22:28:22  Error: Plugin did not respond
22:28:22  
22:28:22  The plugin encountered an error, and failed to respond to the
22:28:22  plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
22:28:22  more details.
22:28:22  
22:28:22  Error: Plugin did not respond
22:28:22  
22:28:22  The plugin encountered an error, and failed to respond to the
22:28:22  plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
22:28:22  more details.
22:28:22  
22:28:22  Error: Plugin did not respond
22:28:22  
22:28:22  The plugin encountered an error, and failed to respond to the
22:28:22  plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
22:28:22  more details.
22:28:22  
22:28:22  Error: Plugin did not respond
22:28:22  
22:28:22  The plugin encountered an error, and failed to respond to the
22:28:22  plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
22:28:22  more details.
22:28:22  
22:28:22  Error: Plugin did not respond
22:28:22  
22:28:22  The plugin encountered an error, and failed to respond to the
22:28:22  plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
22:28:22  more details.
22:28:22  
22:28:22  Error: Plugin did not respond
22:28:22  
22:28:22  The plugin encountered an error, and failed to respond to the
22:28:22  plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
22:28:22  more details.
22:28:22  
22:28:22  Error: Plugin did not respond
22:28:22  
22:28:22  The plugin encountered an error, and failed to respond to the
22:28:22  plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
22:28:22  more details.
22:28:22  
22:28:22  Error: Plugin did not respond
22:28:22  
22:28:22  The plugin encountered an error, and failed to respond to the
22:28:22  plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
22:28:22  more details.
22:28:22  
22:28:22  Error: Plugin did not respond
22:28:22  
22:28:22  The plugin encountered an error, and failed to respond to the
22:28:22  plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
22:28:22  more details.
22:28:22  
22:28:22  Error: Plugin did not respond
22:28:22  
22:28:22  The plugin encountered an error, and failed to respond to the
22:28:22  plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
22:28:22  more details.
22:28:22  
22:28:22  Error: Failure when executing ClaimNetworkDevices
22:28:22  
22:28:22    74: resource "meraki_networks_devices_claim" "net_device_claims" {
22:28:22  
22:28:22  error with operation ClaimNetworkDevices
22:28:22  
22:28:22  Stack trace from the terraform-provider-meraki_v0.2.11-alpha plugin:
22:28:22  
22:28:22  panic: runtime error: invalid memory address or nil pointer dereference
22:28:22  [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd17b13]
22:28:22  
22:28:22  goroutine 229 [running]:
22:28:22  github.com/cisco-open/terraform-provider-meraki/internal/provider.(*NetworksGroupPoliciesRs).toSdkApiRequestUpdate(0xc000790870, {0x18f40c8, 0xc000670b70})
22:28:22  	github.com/cisco-open/terraform-provider-meraki/internal/provider/resource_meraki_networks_group_policies.go:1827 +0x1873
22:28:22  github.com/cisco-open/terraform-provider-meraki/internal/provider.(*NetworksGroupPoliciesResource).Create(0xc0007c0168, {0x18f40c8, 0xc000670b70}, {{{{0x18fbf10, 0xc00082df80}, {0x1376f60, 0xc00077e660}}, {0x190e1e0, 0xc0007f1310}}, {{{0x18fbf10, ...}, ...}, ...}, ...}, ...)
22:28:22  	github.com/cisco-open/terraform-provider-meraki/internal/provider/resource_meraki_networks_group_policies.go:954 +0x65b
22:28:22  github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc0002001e0, {0x18f40c8, 0xc000670b70}, 0xc0004dd580, 0xc0004dd520)
22:28:22  	github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/fwserver/server_createresource.go:101 +0x578
22:28:22  github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xc0005d96d8?, {0x18f40c8, 0xc000670b70}, 0xc000996f50, 0xc0004dd6d8)
22:28:22  	github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/fwserver/server_applyresourcechange.go:57 +0x4a5
22:28:22  github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc0002001e0, {0x18f40c8?, 0xc000670a50?}, 0xc000996eb0)
22:28:22  	github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/proto6server/server_applyresourcechange.go:55 +0x3e5
22:28:22  github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc00020ca00, {0x18f40c8?, 0xc000670270?}, 0xc0001fe000)
22:28:22  	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/tf6server/server.go:865 +0x3d0
22:28:22  github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x15a4c00?, 0xc00020ca00}, {0x18f40c8, 0xc000670270}, 0xc0005c4380, 0x0)
22:28:22  	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:518 +0x169
22:28:22  google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001b5000, {0x18f40c8, 0xc0006701e0}, {0x190c650, 0xc0003f6000}, 0xc000607440, 0xc0003179e0, 0x21941d8, 0x0)
22:28:22  	google.golang.org/grpc@v1.63.2/server.go:1369 +0xe23
22:28:22  google.golang.org/grpc.(*Server).handleStream(0xc0001b5000, {0x190c650, 0xc0003f6000}, 0xc000607440)
22:28:22  	google.golang.org/grpc@v1.63.2/server.go:1780 +0x1016
22:28:22  google.golang.org/grpc.(*Server).serveStreams.func2.1()
22:28:22  	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
22:28:22  created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 20
22:28:22  	google.golang.org/grpc@v1.63.2/server.go:1030 +0x135
22:28:22  
22:28:22  Error: The terraform-provider-meraki_v0.2.11-alpha plugin crashed!

**Expected behavior**
Stable provider that doesn't randomly crash. This operation works some of the time, but is too unstable for us to use in production.

**Debug**
Please provide provider debug. This will help us get a clearer picture of the problem you are having, therefore the solution will be more effective.
To enable debug:
```zsh
export MERAKI_DEBUG=true
export TF_LOG=DEBUG
```

**Environment (please complete the following information):**
* Terraform version:
* Meraki provider version:
* OS Version: 

**Additional context**

**Comment by fmunozmiranda** [comment]
Did you test it with new version?

**Comment by fmunozmiranda** [comment]
if we don´t get answer in next 24 hours issue will be closed.
