### ISSUE TITLE
meraki_networks_alerts_settings not sending muting object

### ISSUE THREAD

**Issue by samspade21** [cisco-open/terraform-provider-meraki#30]
**Prerequisites**
* [X] Have you tested the operation in the API directly?
* [X] Do you have the latest Terraform provider version?
* [X] Review the [compatibility matrix](https://github.com/meraki/terraform-provider-meraki/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
When trying to create a meraki_networks_alerts_settings resource, an error is thrown that the fields for the object muting are not defined.  When using the API, you can create the alert by not sending this object.  The TF resource does not have a schema defined for the object.

``` 
resource "meraki_networks_alerts_settings" "example" {
  network_id = meraki_networks.this.id
  alerts = [{
    type    = "ampMalwareDetected"
    enabled = true
  }]
  default_destinations = {
    all_admins      = true
    emails          = []
    http_server_ids = ["aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDAyRDJLSDZHL0IwNzI3SEdOM0ZELzhiemJZUlNKWmJHQ1FZUUtLMm9NMzg1Ng=="]
    snmp            = false
  }
}
```

**Expected behavior**
Define the muting resource and if not presented, then do not send in the object via the API.

**Screenshots**
![image](https://github.com/cisco-open/terraform-provider-meraki/assets/1037563/5df2368f-6727-46fa-868c-b673960b69ce)
![image](https://github.com/cisco-open/terraform-provider-meraki/assets/1037563/422f9143-f6eb-41f0-87bf-428084dd37d0)

**Environment (please complete the following information):**
* Terraform version: 1.6.0
* Meraki provider version: 0.2.0-alpha
* OS Version: MacOS 14.4.1

**Comment by fmunozmiranda** [comment]
Please try it with new version 2.0.1-alpha.

**Comment by samspade21** [comment]
This has been tested and is working correctly with 2.0.1-alpha.  Thank you very much!
