### ISSUE TITLE
Resource meraki_networks_sensor_alerts_profiles error with operation CreateNetworkSensorAlertsProfile

### ISSUE THREAD

**Issue by samspade21** [cisco-open/terraform-provider-meraki#31]
**Prerequisites**
* [X] Have you tested the operation in the API directly?
* [X] Do you have the latest Terraform provider version?
* [X] Review the [compatibility matrix](https://github.com/meraki/terraform-provider-meraki/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
meraki_networks_sensor_alerts_profiles resource generates an error when trying to create the resource:

```
resource "meraki_networks_sensor_alerts_profiles" "this" {
  serials = ["1234-83H6-ABCD", "1234-4XL4-ABCD"]

  conditions = [
    {
      metric = "temperature"
      duration = 15
      threshold = {
        temperature = {
          quality = "good"
        }
      },
    },
    {
      metric = "humidity"
      duration = 15
      threshold = {
        humidity = {
          quality = "good"
        }
      },
    },
    {
      metric = "water"
      threshold = {
        water = {
          present = true
        }
      }
    }
  ]
  name       = "Sensor Alerts2"
  network_id = meraki_networks.this.id
  recipients = {
    http_server_ids = ["ABCDEFGHIJKLMNOPQRSTUVWXYZ=="]
  }
}

``` 

```
│ Error: Failure when executing CreateNetworkSensorAlertsProfile
│
│   with module.meraki_network.meraki_networks_sensor_alerts_profiles.this,
│   on .terraform/modules/meraki_network/allerts.tf line 37, in resource "meraki_networks_sensor_alerts_profiles" "this":
│   37: resource "meraki_networks_sensor_alerts_profiles" "this" {
│
│ error with operation CreateNetworkSensorAlertsProfile
``` 

**Expected behavior**
The resource should be created

**Screenshots**
![image](https://github.com/cisco-open/terraform-provider-meraki/assets/1037563/a411b7cc-ad6f-4900-8e85-05a4ff3e767f)

![image](https://github.com/cisco-open/terraform-provider-meraki/assets/1037563/60d50c39-40ec-4a32-a2a4-3758685f0b34)

**Environment (please complete the following information):**
* Terraform version: 1.6.0
* Meraki provider version: 0.2.0-alpha
* OS Version: MacOS 14.4.1

**Comment by fmunozmiranda** [comment]
Could you please share me debug of provider?

**Comment by steveAG** [comment]
I work with @samspade21, so this is the same Meraki environment, but a different runspace.
These are collected using provider version 0.2.2-alpha, so the issue is validated with that release as well.

I pared the configuration down to this for logs and tested with a few variants like dropping the water metric and changing the quality value:

```hcl
resource "meraki_networks_sensor_alerts_profiles" "test" {
  serials = ["<SN of an MT10 device>"]

  conditions = [
    {
      metric = "temperature"
      duration = 15
      threshold = {
        temperature = {
          quality = "good"
        }
      },
    },
    {
      metric = "humidity"
      duration = 15
      threshold = {
        humidity = {
          quality = "good"
        }
      },
    },
    {
      metric = "water"
      threshold = {
        water = {
          present = true
        }
      }
    }
  ]
  name       = "Sensor Alerts2"
  network_id = "<Network ID>"
  schedule = null
  recipients = {
    emails = ["<Alert Email>"]
  }
}
```

Debug-level logs: 
[debugLog.txt](https://github.com/user-attachments/files/15537234/debugLog.txt)

**Comment by fmunozmiranda** [comment]
Hey @samspade21  please enable debug..
https://registry.terraform.io/providers/cisco-open/meraki/latest/docs#meraki_debug

And export env var:
export TF_LOG=DEBUG

**Comment by steveAG** [comment]
Hi @fmunozmiranda,

Sorry I missed that there was a provider debug flag, those additional logs helped us easily identify the first issue, which is with our code, the `duration` attribute is an enum, but the provider doesn't validate it before calling the API.

Returning the detailed error from the API would be immensely helpful in situations like this, but that's more of a feature request than anything.
![image](https://github.com/cisco-open/terraform-provider-meraki/assets/12103419/4620d8e4-68c2-496c-966f-318b481ac7b2)

However, creates still fails when a valid duration is provided:

- Using a single `fahrenheit` condition for the temperature threshold fails with the error `Condition with metric=temperature: 'threshold.temperature' object must contain exactly one property; received ['fahrenheit', 'celsius']`
- And a `quality` condition fails with `"Condition with metric=temperature: 'threshold.temperature' object must contain exactly one property; received ['fahrenheit', 'celsius', 'quality']"`

Looking at the request body on line 368 of the logs, the provider inserts a zero value for `fahrenheit` and `celsius` when either value isn't provided.

This code was used with the latest release (0.2.3-alpha) to generate the attached logs:

```hcl
resource "meraki_networks_sensor_alerts_profiles" "test" {
  serials = ["<MT10 SN>"]

  conditions = [
    {
      metric = "temperature"
      duration = 900
      threshold = {
        temperature = {
          quality = "good"
        }
      },
    },
    {
      metric = "humidity"
      duration = 900
      threshold = {
        humidity = {
          quality = "inadequate"
        }
      },
    }
  ]
  name       = "Sensor Alerts2"
  network_id = "<Net ID>"
  schedule = null
  recipients = {
    emails = ["<Alert Email>"]
  }
}
```

Debug log: 
[debugLog.txt](https://github.com/user-attachments/files/15685909/debugLog.txt)

**Comment by fmunozmiranda** [comment]
closed due inactivity. @samspade21 if you still have this issue, please reopen it.

**Comment by samspade21** [comment]
I can confirm this is still an issue with 0.2.12-alpha

**Comment by samspade21** [comment]
I can confirm this is still an issue with 0.2.12-alpha. I can not re-open (not an option for my permissions)
