### ISSUE TITLE
Resource meraki_networks_syslog_servers validation after apply failure.

### ISSUE THREAD

**Issue by finkjordanj** [cisco-open/terraform-provider-meraki#33]
**Prerequisites**
* [X] Have you tested the operation in the API directly?
* [X] Do you have the latest Terraform provider version?
* [X] Review the [compatibility matrix](https://github.com/meraki/terraform-provider-meraki/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
The validation after apply resource `meraki_networks_syslog_servers` errors out with the following error.

│ json: cannot unmarshal string into Go struct field
│ ResponseNetworksUpdateNetworkSyslogServersServers.servers.port of type int

API call appears to be successful as resource is created even with error.

Believe the error is due to the return on the [Go construct ](https://github.com/meraki/dashboard-api-go/blob/4235dfb81430d22794ec67baa86de09f05e55f58/sdk/networks.go#L2672)is set to int but the returned value is a string. 

Return from python lookup.

```
{
    "servers": [
        {
            "host": "162.131.235.183",
            "port": "443",
            "roles": [
                "Appliance event log"
            ]
        }
    ]
}
```

**Expected behavior**
After successful apply expect modification complete message return. 

```
+ resource "meraki_networks_syslog_servers" "this_vmx_hub" {
      + network_id = "<--redacted-->"
      + servers    = [
          + {
              + host  = "<--redacted-->"
              + port  = 443
              + roles = [
                  + "Appliance event log",
                ]
            },
        ]
    }
```
Failure return.

```
╷
│ Error: Failure when executing UpdateNetworkSyslogServers
│ 
│   with module.pfg-managed-meraki-baseline.meraki_networks_syslog_servers.this_vmx_hub[0],
│   on .terraform/modules/pfg-managed-meraki-baseline/main.tf line 218, in resource "meraki_networks_syslog_servers" "this_vmx_hub":
│  218: resource "meraki_networks_syslog_servers" "this_vmx_hub" {
│ 
│ json: cannot unmarshal string into Go struct field
│ ResponseNetworksUpdateNetworkSyslogServersServers.servers.port of type int
╵
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```

**Screenshots**

**Environment (please complete the following information):**
* Meraki Dashboard version: 
* Terraform version: 1.8.3
* Meraki provider version: 0.2.0-alpha
* OS Version: Github runner

**Additional context**

**Comment by fmunozmiranda** [comment]
Please try it with new version 2.0.1-alpha.
