### ISSUE TITLE
Feature Request VMX Support

### ISSUE THREAD

**Issue by kempy007** [cisco-open/terraform-provider-meraki#35]
I would like to see support for creating VMX resources in Meraki. 
I will be defining a new site and add new device and then use token to deploy the Cloud Instance. 
It would be nice to be able to destroy all of this too.

**Additional context**
Postman collection has these API's https://www.postman.com/ciscodevnet/workspace/meraki-workspace/overview

API's:
{{baseUrl}}/organizations/:organizationId/networks
{{baseUrl}}/networks/:networkId/devices/claim/vmx
{{baseUrl}}/devices/:serial/appliance/vmx/authenticationToken

**Comment by obrigg** [comment]
Hello,
Our Terraform Provider is generated from the same OpenAPI spec our documentation and Postman collection are generated from.
In the [DevNet learning lab](https://developer.cisco.com/learning/labs/meraki-dashboard-terraform/your-first-terraform-execution-plan/) I included an explanation for how to find the right Terraform Resource for each API operation. In this case:

I would like to see support for creating VMX resources in Meraki.
I will be defining a new site and add new device and then use token to deploy the Cloud Instance.
It would be nice to be able to destroy all of this too.

Additional context
Postman collection has these API's https://www.postman.com/ciscodevnet/workspace/meraki-workspace/overview

API's:
{{baseUrl}}/organizations/:organizationId/networks >> [meraki_networks](meraki_networks)
{{baseUrl}}/networks/:networkId/devices/claim/vmx >> [meraki_networks_devices_claim_vmx](https://registry.terraform.io/providers/cisco-open/meraki/latest/docs/resources/networks_devices_claim_vmx)
{{baseUrl}}/devices/:serial/appliance/vmx/authenticationToken >> [meraki_devices_appliance_vmx_authentication_token](https://registry.terraform.io/providers/cisco-open/meraki/latest/docs/resources/devices_appliance_vmx_authentication_token)

Good luck.

**Comment by kempy007** [comment]
Thank you
