### ISSUE TITLE
resource "meraki_networks_devices_claim_vmx" Failure

### ISSUE THREAD

**Issue by kempy007** [cisco-open/terraform-provider-meraki#37]
**Prerequisites**
* [X] Have you tested the operation in the API directly?
* [X] Do you have the latest Terraform provider version?
* [404] Review the [compatibility matrix](https://github.com/meraki/terraform-provider-meraki/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
Trying to use resource "meraki_networks_devices_claim_vmx" and resource "meraki_devices_appliance_vmx_authentication_token" 
Getting failures due to type errors

**Expected behavior**
TF Provider to successfully create the VMX claim and create the subsequent token.

Postman works as expected.

**Environment:**
Terraform v1.8.2
on darwin_arm64
+ provider registry.terraform.io/cisco-open/meraki v0.2.0-alpha

**Additional context**

### claim
│ An unexpected error was encountered while verifying an attribute value matched its
│ expected type to prevent unexpected behavior or panics. This is always an error in the
│ provider. Please report the following to the provider developer:
│ 
│ Expected framework type from provider logic: types.ListType[basetypes.StringType] /
│ underlying type: tftypes.List[tftypes.String]
│ Received framework type from provider logic: types.SetType[basetypes.StringType] /
│ underlying type: tftypes.Set[tftypes.String]
│ Path: item.tags

### token
meraki_devices_appliance_vmx_authentication_token.test_this: Creating...
╷
│ Error: Value Conversion Error
│ 
│   with meraki_devices_appliance_vmx_authentication_token.test_this,
│ An unexpected error was encountered trying to convert tftypes.Value into
│ provider.DevicesApplianceVmxAuthenticationToken. This is always an error in the
│ provider. Please report the following to the provider developer:
│ 
│ mismatch between struct and object: Struct defines fields not found in object:
│ parameters.

**Comment by fmunozmiranda** [comment]
Hi @kempy007 could you please try it again with v0.2.2-apha and update if it works now?

**Comment by kempy007** [comment]
@fmunozmiranda reviewing

**Comment by kempy007** [comment]
@fmunozmiranda 
The claim now works!
The Token still fails.
```
│ Error: Value Conversion Error
│ 
│   with meraki_devices_appliance_vmx_authentication_token.test_this,
│ An unexpected error was encountered trying to convert tftypes.Value into
│ provider.DevicesApplianceVmxAuthenticationToken. This is always an error in the provider.
│ Please report the following to the provider developer:
│ 
│ mismatch between struct and object: Struct defines fields not found in object:
│ parameters.
```

**Comment by kempy007** [comment]
refreshing/re-apply plan get more errors. Destroy is ok.

```
│ Warning: Error deleting Resource
│ 
│ This resource has no delete method in the meraki lab, the resource was deleted only in
│ terraform.
╵
╷
│ Warning: Error deleting Resource
│ 
│   with meraki_networks_devices_claim_vmx.branstf,
│   on main.tf line 42, in resource "meraki_networks_devices_claim_vmx" "branstf":
│   42: resource "meraki_networks_devices_claim_vmx" "branstf" { # TODO: Ticket logged not working
│ 
│ This resource has no delete method in the meraki lab, the resource was deleted only in
│ terraform.
╵
╷
│ Error: Failure when executing VmxNetworkDevicesClaim
│ 
│   with meraki_networks_devices_claim_vmx.branstf,
│   on main.tf line 42, in resource "meraki_networks_devices_claim_vmx" "branstf":
│   42: resource "meraki_networks_devices_claim_vmx" "branstf" { # TODO: Ticket logged not working
│ 
│ error with operation VmxNetworkDevicesClaim
```

**Comment by fmunozmiranda** [comment]
@kempy007  Sorry I don´t see the token error of token..
Let me check it and update you to try it again.

**Comment by fmunozmiranda** [comment]
@kempy007 please try it again with new version.

**Comment by kempy007** [comment]
@fmunozmiranda Ok the token now works. 

I have started to move the goal a bit here and added more features I need. 
I am seeing problems refreshing the plan on 2nd & 3rd apply, it errors like below with some resources. Do you wan't me to add to this ticket or a new ticket?

```
 Warning: Error deleting Resource
│ 
│   with meraki_networks_devices_claim_vmx.claim,
│   on main.tf line 47, in resource "meraki_networks_devices_claim_vmx" "claim":
│   47: resource "meraki_networks_devices_claim_vmx" "claim" {
│ 
│ This resource has no delete method in the meraki lab, the resource was deleted only in terraform.
│ 
│ (and one more similar warning elsewhere)
╵
╷
│ Error: Failure when executing UpdateNetworkFirmwareUpgrades
│ 
│   with meraki_networks_firmware_upgrades.update_firmware,
│   on main.tf line 71, in resource "meraki_networks_firmware_upgrades" "update_firmware":
│   71: resource "meraki_networks_firmware_upgrades" "update_firmware" {
│ 
│ error with operation UpdateNetworkFirmwareUpgrades
```

**Comment by fmunozmiranda** [comment]
Yes please open new issues and pass us debug file
https://registry.terraform.io/providers/cisco-open/meraki/latest/docs#meraki_debug
And export env var:
export TF_LOG=DEBUG

**Comment by kempy007** [comment]
@fmunozmiranda logged private ticket to TAC Case 11849828
