### ISSUE TITLE
meraki_devices_management_interface - constant update

### ISSUE THREAD

**Issue by samspade21** [cisco-open/terraform-provider-meraki#48]
**Prerequisites**
* [X] Have you tested the operation in the API directly?
* [X] Do you have the latest Terraform provider version?
* [X] Review the [compatibility matrix](https://github.com/meraki/terraform-provider-meraki/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
When applying a **meraki_devices_management_interface** resource on an MX250, the ddns_hostnames.active_ddns_hostname, ddns_hostnames.ddns_hostname_wan1, ddns_hostnames.ddns_hostname_wan2, wan1.vlan, wan2.static_dns, and wan2.vlan must be re-applied each time with a "known after apply" value.  While this does not break anything (the apply works correctly) a terraform plan shows that changes will be made - when none actually are.

```
resource "meraki_devices_management_interface" "sample_firewall_interface" {
  serial = "Q2XX-1234-ABCD"

  wan1 = {
    using_static_ip    = true
    static_ip          = "192.168.1.2"
    static_gateway_ip  = "192.168.1.1"
    static_subnet_mask = "255.255.255.0"
    static_dns         = ["8.8.8.8", "8.8.4.4"]
    vlan               = null
    wan_enabled        = "enabled"
  }

  wan2 = {
    using_static_ip    = false
    wan_enabled        = "enabled"
  }
}
``` 

**Expected behavior**
No need to run an apply, as nothing is changing after each run.

**Screenshots**
![image](https://github.com/cisco-open/terraform-provider-meraki/assets/1037563/f417b017-611f-43e9-a21f-5776b04c5207)

**Environment (please complete the following information):**
* Meraki Dashboard version: 1.43.0
* Terraform version: 1.6
* Meraki provider version: 0.2.1-alpha
* OS Version: MacOS 14.5 (23F79)

**Additional context**
NA

**Comment by fmunozmiranda** [comment]
Hi @samspade21 I try it with version 0.2.1-alpha and it works for me, are you using last version?

**Comment by samspade21** [comment]
We had meraki_networks_appliance_settings dynamic_dns disabled.  That was the cause of the constant reapply.  Once enabled - this issue went away.  Thank you!
