### ISSUE TITLE
Invalid Go Module Name

### ISSUE THREAD

**Issue by iwahbe** [cisco-open/terraform-provider-meraki#49]
**Describe the bug**

[Go's module documentation](https://go.dev/doc/modules/layout) suggests that module [paths](https://go.dev/ref/mod#module-path) should be of the form

```
github.com/cisco-open/terraform-provider-meraki
^          ^          ^
VCS URL    ORG        REPO
```

Currently, it is

https://github.com/cisco-open/terraform-provider-meraki/blob/9b712fa00fbd4b6978f8e3864b7fa64368994e8c/go.mod#L1

**Expected behavior**

The module name (in `go.mod`) is `github.com/cisco-open/terraform-provider-meraki`

**Additional context**

I work at [Pulumi](https://www.pulumi.com) and maintain [pulumi-meraki](https://github.com/pulumi/pulumi-meraki) (which is based off of [terraform-provider-meraki](https://github.com/cisco-open/terraform-provider-meraki)) for a shared customer. We have tooling to automatically detect provider upgrades that expects the module name to be standard.

I have opened a PR to address this issue: #41

**Comment by fmunozmiranda** [comment]
Changed.
