### ISSUE TITLE
resource `meraki_networks_webhooks_http_servers` marked as tainted and results in an error after creating

### ISSUE THREAD

**Issue by zbuchheit** [cisco-open/terraform-provider-meraki#72]
**Prerequisites**
* [ ] Have you tested the operation in the API directly?
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/meraki/terraform-provider-meraki/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
When attempting to create `meraki_networks_webhooks_http_servers` I get an error after the resource is created and it is marked as tainted. The error I get is the following.

```
[ERROR] vertex "meraki_networks_webhooks_http_servers.webhook_http_server" error: Provider produced inconsistent result after apply
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to meraki_networks_webhooks_http_servers.webhook_http_server, provider "provider[\"registry.terraform.io/cisco-open/meraki\"]" produced an unexpected new value:
│ .http_server_id: was null, but now cty.StringVal("redacted").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

**Expected behavior**
I expect the resource to be created successfully without issue and be able to continue to be managed by TF.

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.

**Environment (please complete the following information):**
* Meraki Dashboard version: 
* Terraform version: Terraform v1.8.5
* Meraki provider version: v0.2.3-alpha
* OS Version: 

**Additional context**

## Example TF Program
```TF
terraform {
  required_providers {
    meraki = {
      source = "cisco-open/meraki"
      version = "0.2.3-alpha"
    }
  }
}

provider "meraki" {
  meraki_debug = "true"
}

resource "meraki_networks_webhooks_http_servers" "webhook_http_server" {
  name = "Pulumi Test Webhook"
  url = "https://example.com/test"
  network_id = "redacted"
  shared_secret = "redactedSecret"
  payload_template = {
    name = "Meraki (included)"
    payload_template_id = "wpt_00001"
  }
}
```

**Comment by fmunozmiranda** [comment]
closed due inactivity. @zbuchheit if you still have this issue, please reopen it.
