### ISSUE TITLE
Resource `meraki_networks_wireless_rf_profiles` error when trying to create new profile

### ISSUE THREAD

**Issue by tienphan181** [cisco-open/terraform-provider-meraki#88]
**Describe the bug**
When attempting to create a `meraki_networks_wireless_rf_profiles` resource I get the following error:
`│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-meraki_v0.2.5-alpha plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xdca1f1]

goroutine 66 [running]:
github.com/go-resty/resty/v2.(*Response).StatusCode(...)
	github.com/go-resty/resty/v2@v2.13.1/response.go:66
github.com/cisco-open/terraform-provider-meraki/internal/provider.(*NetworksWirelessRfProfilesResource).Create(0xc000726040, {0x18c03e8, 0xc00048bc80}, {{{{0x18c8070, 0xc00049f5f0}, {0x1351300, 0xc00049de60}}, {0x18da340, 0xc0007720a0}}, {{{0x18c8070, ...}, ...}, ...}, ...}, ...)
	github.com/cisco-open/terraform-provider-meraki/internal/provider/resource_meraki_networks_wireless_rf_profiles.go:1507 +0x3b1
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc000338340, {0x18c03e8, 0xc00048bc80}, 0xc00034f580, 0xc00034f520)
	github.com/hashicorp/terraform-plugin-framework@v1.7.0/internal/fwserver/server_createresource.go:101 +0x578
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xc00034f6d8, {0x18c03e8, 0xc00048bc80}, 0xc0003f23c0, 0xc00034f6d8)
	github.com/hashicorp/terraform-plugin-framework@v1.7.0/internal/fwserver/server_applyresourcechange.go:57 +0x4a5
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc000338340, {0x18c03e8, 0xc00048bb60}, 0xc0003f2320)
	github.com/hashicorp/terraform-plugin-framework@v1.7.0/internal/proto6server/server_applyresourcechange.go:55 +0x3e5
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc00023e8c0, {0x18c03e8, 0xc00048aff0}, 0xc000376380)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/tf6server/server.go:865 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x157a340, 0xc00023e8c0}, {0x18c03e8, 0xc00048aff0}, 0xc000529d00, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:518 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001b9000, {0x18c03e8, 0xc00048e180}, {0x18d87b8, 0xc00036e000}, 0xc000518000, 0xc00032b980, 0x21521b8, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc0001b9000, {0x18d87b8, 0xc00036e000}, 0xc000518000)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0x1016
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 25
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x135

Error: The terraform-provider-meraki_v0.2.5-alpha plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.`

**Expected behavior**
I would expect the new resource to be recreated.

**Screenshots**

**Environment (please complete the following information):**
* Meraki Dashboard version: 
* Terraform version:  OpenTofu v1.7.2
* Meraki provider version: 0.2.5-alpha
* OS Version: macOS 13.6.7

**Comment by mcparaf** [comment]
bump, same happened to me

**Comment by fmunozmiranda** [comment]
@tienphan181 please try it again with new version and update us.

**Comment by tienphan181** [comment]
Hi @fmunozmiranda, 
I tried it with the new version and got a couple new errors: 

`│ Error: Value Conversion Error
│ 
│   with data.meraki_networks_wireless_rf_profiles.example,
│   on rf-profiles.tf line 1, in data "meraki_networks_wireless_rf_profiles" "example":
│    1: data "meraki_networks_wireless_rf_profiles" "example" {
│ 
│ An unexpected error was encountered while verifying an attribute value
│ matched its expected type to prevent unexpected behavior or panics. This is
│ always an error in the provider. Please report the following to the
│ provider developer:
│ 
│ Expected framework type from provider logic:
│ types.ListType[basetypes.StringType] / underlying type:
│ tftypes.List[tftypes.String]
│ Received framework type from provider logic:
│ types.SetType[basetypes.StringType] / underlying type:
│ tftypes.Set[tftypes.String]
│ Path: item.ap_band_settings.bands.enabled`

**This is one regarding 5ghz valid auto channels:**
`│ Error: Value Conversion Error
│ 
│   with data.meraki_networks_wireless_rf_profiles.example,
│   on rf-profiles.tf line 1, in data "meraki_networks_wireless_rf_profiles" "example":
│    1: data "meraki_networks_wireless_rf_profiles" "example" {
│ 
│ An unexpected error was encountered trying to convert from struct into an
│ object. This is always an error in the provider. Please report the
│ following to the provider developer:
│ 
│ Mismatch between struct and object type: Struct defines fields not found in
│ object: valid_auto_channels.
│ Struct: provider.ResponseWirelessGetNetworkWirelessRfProfileFiveGhzSettings
│ Object type: types.ObjectType["channel_width":basetypes.StringType,
│ "max_power":basetypes.Int64Type, "min_bitrate":basetypes.Int64Type,
│ "min_power":basetypes.Int64Type, "rxsop":basetypes.Int64Type]`

**2.4ghz config error:** 
`│ Error: Value Conversion Error
│ 
│   with data.meraki_networks_wireless_rf_profiles.example,
│   on rf-profiles.tf line 1, in data "meraki_networks_wireless_rf_profiles" "example":
│    1: data "meraki_networks_wireless_rf_profiles" "example" {
│ 
│ An unexpected error was encountered while verifying an attribute value
│ matched its expected type to prevent unexpected behavior or panics. This is
│ always an error in the provider. Please report the following to the
│ provider developer:
│ 
│ Expected framework type from provider logic:
│ types.SetType[basetypes.StringType] / underlying type:
│ tftypes.Set[tftypes.String]
│ Received framework type from provider logic:
│ types.SetType[basetypes.Int64Type] / underlying type:
│ tftypes.Set[tftypes.Number]
│ Path: item.two_four_ghz_settings.valid_auto_channels
`

**Data Source error:** 
`╷
│ Error: Value Conversion Error
│ 
│   with data.meraki_networks_wireless_rf_profiles.example,
│   on rf-profiles.tf line 1, in data "meraki_networks_wireless_rf_profiles" "example":
│    1: data "meraki_networks_wireless_rf_profiles" "example" {
│ 
│ An unexpected error was encountered trying to convert from struct value.
│ This is always an error in the provider. Please report the following to the
│ provider developer:
│ 
│ error retrieving field names from struct tags: item.per_ssid_settings.0:
│ invalid field name, must only use lowercase letters, underscores, and
│ numbers, and must start with a letter`

Thanks!

**Comment by tienphan181** [comment]
@fmunozmiranda attached is my config. 
[wireless_rf_profiles.txt](https://github.com/user-attachments/files/16255491/wireless_rf_profiles.txt)

**Comment by fmunozmiranda** [comment]
Could you help us sharing the provider DEBUG?

**Comment by efernando87** [comment]
Hi Guys @fmunozmiranda and @tienphan181 , 

i am having the same issue here. and i found out that if I configure the **per_ssid_settings** on the initial resource creation, the script will fail. but if we are not using that attribute on the initial setup. it works.

so in my case the initial setup the terraform can run successfully if i am just using this parameter:
`resource "meraki_networks_wireless_rf_profiles" "test-Terraform-RF" {
  network_id           = meraki_networks.network.network_id
  band_selection_type      = "ap"
  client_balancing_enabled = false
  name                     = "test Indoor Profile"
  five_ghz_settings = {
    channel_width = "20"
    max_power     = 30
    min_bitrate   = 24
    min_power     = 12
  }
  two_four_ghz_settings = {
    ax_enabled  = true
    max_power   = 30
    min_bitrate = 24
    min_power   = 8
  }
  ap_band_settings = {
    band_operation_mode   = "dual"
    band_steering_enabled = true
    bands = {
      enabled = ["2.4", "5"]
    }
  }
}
`

then after the resource create successfully i change it to this:

```
resource "meraki_networks_wireless_rf_profiles" "test-Terraform-RF" {
  network_id           = meraki_networks.network.network_id
  band_selection_type      = "ssid"
  client_balancing_enabled = false
  name                     = "Test Indoor Profile"
  five_ghz_settings = {
    channel_width = "20"
    max_power     = 30
    min_bitrate   = 24
    min_power     = 12
  }
  two_four_ghz_settings = {
    ax_enabled  = true
    max_power   = 30
    min_bitrate = 24
    min_power   = 8
  }
  per_ssid_settings = {
    status_0 = {
      band_operation_mode   = "dual"
      band_steering_enabled = true
      bands = {
        enabled = ["2.4", "5"]
      }
    }
    status_1 = {
      band_operation_mode   = "2.4ghz"
      band_steering_enabled = false
      bands = {
        enabled = ["2.4"]
      }
    }
    status_2  = local.standard_pssid
    status_3  = local.standard_pssid
    status_4  = local.standard_pssid
    status_5  = local.standard_pssid
    status_6  = local.standard_pssid
    status_7  = local.standard_pssid
    status_8  = local.standard_pssid
    status_9  = local.standard_pssid
    status_10 = local.standard_pssid
    status_11 = local.standard_pssid
    status_12 = local.standard_pssid
    status_13 = local.standard_pssid
    status_14 = local.standard_pssid
  }
}
```

but if I run the second one as the initial one, then the script will failed

**Comment by fmunozmiranda** [comment]
@efernando87 please help us with DEBUG of provider.

**Comment by tienphan181** [comment]
@fmunozmiranda I attached the debug logs. 
[rf.log](https://github.com/user-attachments/files/16338732/rf.log)

Thanks!

**Comment by fmunozmiranda** [comment]
@tienphan181 please see this API message:
<img width="1356" alt="image" src="https://github.com/user-attachments/assets/ee3e5b23-70be-4408-aba9-8e0faf764255">

**Comment by tienphan181** [comment]
@fmunozmiranda I just have the code as the example in the documentation. Since this is our production environment I would like to output the current data source to see the current code so I could do an import command. I get the below error when I try to do data source output. 

`╷
│ Error: Value Conversion Error
│ 
│   with data.meraki_networks_wireless_rf_profiles.example,
│   on rf-profiles.tf line 1, in data "meraki_networks_wireless_rf_profiles" "example":
│    1: data "meraki_networks_wireless_rf_profiles" "example" {
│ 
│ An unexpected error was encountered trying to convert from struct into an
│ object. This is always an error in the provider. Please report the
│ following to the provider developer:
│ 
│ Mismatch between struct and object type: Struct defines fields not found in
│ object: valid_auto_channels.
│ Struct: provider.ResponseWirelessGetNetworkWirelessRfProfileFiveGhzSettings
│ Object type: types.ObjectType["channel_width":basetypes.StringType,
│ "max_power":basetypes.Int64Type, "min_bitrate":basetypes.Int64Type,
│ "min_power":basetypes.Int64Type, "rxsop":basetypes.Int64Type]` 


My code:

`data "meraki_networks_wireless_rf_profiles" "example" {
  network_id                = meraki_networks.xxx.id
  rf_profile_id = "xxxx"
}

output "meraki_networks_wireless_rf_profiles_example" {
  value = data.meraki_networks_wireless_rf_profiles.example.item
}`

**Comment by fmunozmiranda** [comment]
Hi, please try it again with new version.
