### ISSUE TITLE
meraki_networks_appliance_traffic_shaping_rules rules.definitions type application category is not working

### ISSUE THREAD

**Issue by efernando87** [cisco-open/terraform-provider-meraki#93]
**Prerequisites**
* [V] Have you tested the operation in the API directly?
* [V] Do you have the latest Terraform provider version?
* [V] Review the [compatibility matrix](https://github.com/meraki/terraform-provider-meraki/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
unable to config sdwan traffic shaping if using the type application & application category as the value required to be string but on the docs it says a map value.
here is what i am try to configure on the definitions:
      definitions = [{
        type  = "application"
        value = {
            id = "meraki:layer7/application/374" # have tried using this format { "id": "meraki:layer7/…" } also not works
            }
        }
      ]
and here is the error message:
Inappropriate value for attribute "rules": element 2: attribute "definitions": element 0: attribute "value": string required.

this also relate to the similar data plugin that also giving error output when we use it to get the existing configuration if it is contain the application or application category on the rules.definitions.type

**Expected behavior**
expectation is we can use this plugins to configure the traffic shaping using the type application category & application

**Screenshots**

Error: Incorrect attribute value type
│ 
│   on ../Module-Networks/qos.tf line 5, in resource "meraki_networks_appliance_traffic_shaping_rules" "standard_qos":
│    5:   rules = [
│    6:     {
│    7:       definitions = [
│    8:         {
│    9:           type  = "host"
│   10:           value = "meet.google.com"
│   11:         },
│   12:         {
│   13:           type  = "host"
│   14:           value = "zoom.us"
│   15:         },
│   16:       ]
│   17:       dscp_tag_value = 34
│   18:       per_client_bandwidth_limits = {
│   19:         bandwidth_limits = {
│   20:           limit_down = null
│   21:           limit_up   = null
│   22:         }
│   23:         settings = "ignore"
│   24:       }
│   25:       priority = "high"
│   26:     },
│   27:     {
│   28:       definitions = [{
│   29:         type  = "host"
│   30:         value = "google.com"
│   31:         },
│   32:         {
│   33:           type  = "ipRange"
│   34:           value = "143.92.82.0/24"
│   35:         },
│   36:       ]
│   37:       dscp_tag_value = 26
│   38:       per_client_bandwidth_limits = {
│   39:         bandwidth_limits = {
│   40:           limit_down = null
│   41:           limit_up   = null
│   42:         }
│   43:         settings = "ignore"
│   44:       }
│   45:       priority = "normal"
│   46:     },
│   47:     {
│   48:       definitions = [{
│   49:         type  = "application"
│   50:         value = {
│   51:             id = "meraki:layer7/application/374"
│   52:             }
│   53:         }
│   54:       ]
│   55:       dscp_tag_value = 12
│   56:       per_client_bandwidth_limits = {
│   57:         bandwidth_limits = {
│   58:           limit_down = 1536
│   59:           limit_up   = 1536
│   60:         }
│   61:         settings = "custom"
│   62:       }
│   63:       priority = "low"
│   64:     }
│   65:   ]
│ 
│ Inappropriate value for attribute "rules": element 2: attribute "definitions": element 0: attribute "value": string required.

**Environment (please complete the following information):**
* Meraki Dashboard version: 
* Terraform version: v1.8.3
* Meraki provider version: 0.2.5-alpha
* OS Version: 

**Additional context**

**Comment by fmunozmiranda** [comment]
Please try it again with new version and see this:
https://github.com/cisco-open/terraform-provider-meraki/blob/main/examples/samples/resources/meraki_networks_appliance_traffic_shaping_rules/resource.tf

**Comment by fmunozmiranda** [comment]
If we do not receive a response it will be closed in the next 24 hours.
