### ISSUE TITLE
meraki_networks_appliance_warm_spare got error with operation UpdateNetworkApplianceWarmSpare

### ISSUE THREAD

**Issue by efernando87** [cisco-open/terraform-provider-meraki#95]
**Prerequisites**
* [V] Have you tested the operation in the API directly?
* [V] Do you have the latest Terraform provider version?
* [V] Review the [compatibility matrix](https://github.com/meraki/terraform-provider-meraki/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
unable to config MX warm spare and got error with operation UpdateNetworkApplianceWarmSpare

**Expected behavior**
can update and add the warm spare 

**Screenshots**
below are the tf script and the result

```
resource "meraki_networks_appliance_warm_spare" "secondary_mx" {
   count        = local.create_network && var.secondary_mx_serial != "" ? 1 : 0
   enabled      = true
   network_id   = meraki_networks.network[0].network_id
   spare_serial = var.secondary_mx_serial
}
```
result

```
 Error: Failure when executing UpdateNetworkApplianceWarmSpare
│ 
│   with module.network.meraki_networks_appliance_warm_spare.secondary_mx[0],
│   on ../Module-Networks/devices.tf line 26, in resource "meraki_networks_appliance_warm_spare" "secondary_mx":
│   26: resource "meraki_networks_appliance_warm_spare" "secondary_mx" {
│ 
│ error with operation UpdateNetworkApplianceWarmSpare
```

**Environment (please complete the following information):**
* Meraki Dashboard version: 
* Terraform version: 1.8.3
* Meraki provider version: 0.2.5-alpha
* OS Version: 

**Additional context**

**Comment by fmunozmiranda** [comment]
Could you activate the provider debug and share it?

```hcl
provider "meraki" {
  meraki_debug = "true"
}
```
```zsh
export TF_LOG="DEBUG"
```

I test it and it works for me.

**Comment by efernando87** [comment]
Hi @fmunozmiranda ,

debug attached.

thanks for your help
[terraform meraki debug log.txt](https://github.com/user-attachments/files/16172314/terraform.meraki.debug.log.txt)

**Comment by fmunozmiranda** [comment]
See this: 
<img width="819" alt="image" src="https://github.com/cisco-open/terraform-provider-meraki/assets/93611708/9c74ef14-ad69-4eaf-addd-9fd4da79579a">

Looks like it's an API bug.

**Comment by efernando87** [comment]
hmmmm so the uplink mode might be required attribute instead of optional?

let me try

**Comment by efernando87** [comment]
it is working now when i add the attribute "uplinkMode"

just need your help on this related issue: https://github.com/cisco-open/terraform-provider-meraki/issues/99

because after spare added, the next terraform run will hit this issue.

**Comment by fmunozmiranda** [comment]
Ok, Closing this one to see the another one
