### ISSUE TITLE
networks_switch_dhcp_server_policy_arp_inspection_trusted_servers - inconsistency

### ISSUE THREAD

**Issue by mcparaf** [cisco-open/terraform-provider-meraki#96]
**Prerequisites**
* [ v ] Have you tested the operation in the API directly?
* [ v ] Do you have the latest Terraform provider version?
* [ x ] Review the [compatibility matrix](https://github.com/meraki/terraform-provider-meraki/tree/main#compatibility-matrix) before opening an issue. - this page does not exist

**Describe the bug**
After trying to add any trusted server via the provider this happens:
```
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.meraki.meraki_networks_switch_dhcp_server_policy_arp_inspection_trusted_servers.net_switch_dhcp_server_policy_arp_inspection_trusted_servers["L_709316941310853998"], provider
│ "module.meraki.provider[\"registry.terraform.io/cisco-open/meraki\"]" produced an unexpected new value: .network_id: was cty.StringVal("L_709316941310853998"), but now null.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```
This also breaks the terraform state. I have to manually remove the trusted server field from terraform.tfstate in order to restore any kind of functionality. After trying to create this resource the provider also is unable to download data about trusted servers because it tries to access the wrong URL: `GET  /api/v1/networks//switch/dhcpServerPolicy/arpInspection/trustedServers`

**Expected behavior**
This should create a resource in the API.

**Screenshots**
This breaks before any API call is made.

**Environment (please complete the following information):**
* Meraki Dashboard version: the current version at https://n260.meraki.com
* Terraform version: 1.9.1
* Meraki provider version: 0.2.5-alpha
* OS Version: macOS Sonoma 14.5

**Comment by fmunozmiranda** [comment]
@mcparaf  please try it again with new version and update us.

**Comment by fmunozmiranda** [comment]
If we do not receive a response it will be closed in the next 24 hours.
